In [2]:
using Combinatorics

┌ Info: Precompiling Combinatorics [861a8166-3701-5b0c-9a16-15d98fcdc6aa]
└ @ Base loading.jl:1278


##  Read data

In [3]:
f = open("input.txt");
data = readlines(f);

In [10]:
data_int = [ parse(Int64, data[i]) for i in 1:length(data)]

200-element Array{Int64,1}:
 1977
 1802
 1856
 1309
 2003
 1854
 1898
 1862
 1857
  542
 1616
 1599
 1628
    ⋮
 1283
 1687
 1220
 1443
 1409
 1252
 1506
 1742
 1319
 1882
  951
 1849

In [13]:
combins = collect(combinations(data_int, 2));
combins = permutedims(reshape(hcat(combins...), (length(combins[1]), length(combins))));

## Detect which pair and compute answer

In [27]:
sum_combins = combins[:, 1] + combins[:, 2]

19900-element Array{Int64,1}:
 3779
 3833
 3286
 3980
 3831
 3875
 3839
 3834
 2519
 3593
 3576
 3605
 3488
    ⋮
 2457
 3355
 3061
 3624
 2693
 3591
 3201
 2270
 3168
 2833
 3731
 2800

In [36]:
row_2020 = findall(a->a == 2020, sum_combins);
answer = combins[row_2020, 1] .* combins[row_2020, 2]

1-element Array{Int64,1}:
 41979

# Part 2

In [40]:
combins3 = collect(combinations(data_int, 3));
combins3 = permutedims(reshape(hcat(combins3...), (length(combins3[1]), length(combins3))));

In [44]:
sum_combins3 = combins3[:, 1] + combins3[:, 2] + combins3[:, 3]

1313400-element Array{Int64,1}:
 5635
 5088
 5782
 5633
 5677
 5641
 5636
 4321
 5395
 5378
 5407
 5290
 5627
    ⋮
 5237
 4306
 4943
 4012
 4910
 4575
 5473
 4542
 4152
 5050
 4119
 4682

In [45]:
row_2020_3 = findall(a->a == 2020, sum_combins3)

1-element Array{Int64,1}:
 576642

In [46]:
answer_3 = combins3[row_2020_3, 1] .* combins3[row_2020_3, 2] .* combins3[row_2020_3, 3]

1-element Array{Int64,1}:
 193416912